name: Selenium Web Checker

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # Ejecuta cada 5 minutos

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3  # Actualizado a v3

      - name: Set up Python
        uses: actions/setup-python@v4  # Actualizado a v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the Selenium script
        run: |
          python Scrips/selenium_test.py
